name: Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
         java-version: '21'

    - name: Build Project
      run: mvn clean install

    - name: Run Tests
      run: mvn test

     
