name: Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'  # Add this line
        overwrite-settings: true

    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Run tests
      run: ./gradlew test
